### ISSUE TITLE
Add XBOX DXC Compiler Support via Shader Macro

### ISSUE THREAD

**Issue by stonstad** [FrenzyByte/fluidfrenzy#11]
- [ ] Add conditional support for the DXC shader compiler.  The condition may be SHADER_API_XBOXONE or a predefined macro for PC users that wish to use the DXC compiler.

e.g. 
#if SHADER_API_D3D12 && SHADER_API_XBOXONE
   #pragma use_dxc
#endif

- [ ] Resolve computation/shader functionality which is not XBOX console compatible.

![image](https://github.com/user-attachments/assets/a041838f-c13a-4f53-a7a3-5e58284c309e)
![image](https://github.com/user-attachments/assets/bc5f4431-3080-49ba-bed5-59ea9967dcb0)

**Comment by FrenzyByte** [comment]
The compile errors have been fixed and DXC support has been added under the SHADER_API_XBOXONE macro Unfortunately Unity does not yet distinguish between DX11 and DX12 in shaders as per: [link](https://discussions.unity.com/t/editor-d3d11-vs-d3d12-compiling/913980) so the use_dxc flag will only work on XBOX by default but will have to manually be turned on if used on PC by uncommenting the FORCE_DXC define.

This will be released on version v1.0.6 in the next few days.
