### ISSUE TITLE
Expose Configuration for Simulation Y-Value Offset

### ISSUE THREAD

**Issue by stonstad** [FrenzyByte/fluidfrenzy#12]
- [ ] Beyond regular clipping, a mechanism is needed to offset the simulation from the y-axis.  This capability accommodates tessellated terrain and other behaviors which may require a y-axis offset.

![image](https://github.com/user-attachments/assets/db6d4c4a-3f36-4f1f-8f05-11064eed1049)

**Comment by FrenzyByte** [comment]
Added in version v1.0.6
