### ISSUE TITLE
Question about foam

### ISSUE THREAD

**Issue by caplayz** [FrenzyByte/fluidfrenzy#14]
Im currently working on a system like this for another engine. My question is how did you get the foam to work? Like what papers and how did it generate and all that stuff.

Thanks

**Comment by FrenzyByte** [comment]
Hi, my foam is a mask that is generated by the fluid simulation. The mask currently uses 2 channels of a rendertarget
The red channel adds foam based on the angle of the wave and velocity in the Y direction.
The green channel adds foam based on the pressure within the fluid simulation. Pressure is calculated using this paper: https://developer.nvidia.com/gpugems/gpugems/part-vi-beyond-triangles/chapter-38-fast-fluid-dynamics-simulation-gpu

These 2 channels are then advected similar to the paper above to move the foam within the mask.

There is also some linear and exponential decay over time to fade out the foam.

This mask is read by the water shader to apply a the amount of foam. I use a albedo texture as a extra mask for foam and light it using PBR. The foam textures are flow mapped based on the velocity of the fluid.
