### ISSUE TITLE
Demand: Inundation Analysis

### ISSUE THREAD

**Issue by xwq-git** [FrenzyByte/fluidfrenzy#15]
We want to achieve the effect of flooding analysis on oblique photographic data！Mesh type：MeshCollider!  Thanks!
![effect picture](https://github.com/user-attachments/assets/de75977c-33f9-4afc-95f8-74dc8995a763)

**Comment by FrenzyByte** [comment]
I will try to add this in the next version but please keep in mind that since the simulation is done on a grid, the look might not be fully accurate with high detail meshes as they will not be able to match the simulation grid perfectly..

**Comment by FrenzyByte** [comment]
v1.1.1 is submitted and has support for assigning a MeshCollider as the base ground for the Fluid Simulation. Awaiting Unity approval and expecting it to go live in the next few days.

**Comment by FrenzyByte** [comment]
v1.1.1 is released which has support for MeshColliders as input..

**Comment by xwq-git** [comment]
Wow,thank sir! But the effect is not as good as on the unity terrain.

**Comment by FrenzyByte** [comment]
I might be able to improve on this if you have any example meshes you wish to use.  I mainly tested this by using this converter on my terrain meshes: https://assetstore.unity.com/packages/tools/terrain/mesh-terrain-editor-free-67758 which is why for my did matched closely, but if you have higher/lower detail meshes that don't match a grid it might be trickier. 

A example scene could help me improve it if you could provide it (does not need to be your real project, just a concept of how your meshes look).

**Comment by xwq-git** [comment]
Hopefully, water can flow on this mesh,thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FrenzyByte/fluidfrenzy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月30日(星期一) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FrenzyByte/fluidfrenzy] Demand: Inundation Analysis (Issue #15)





 
I might be able to improve on this if you have any example meshes you wish to use.  I mainly tested this by using this converter on my terrain meshes: https://assetstore.unity.com/packages/tools/terrain/mesh-terrain-editor-free-67758 which is why for my did matched closely, but if you have higher/lower detail meshes that don't match a grid it might be trickier.
 
A example scene could help me improve it if you could provide it (does not need to be your real project, just a concept of how your meshes look).
